=== clarity-h2020/data-package/schemas/profiles/clarity-data-package.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"$id": "https://raw.githubusercontent.com/clarity-h2020/data-package/master/schemas/profiles/clarity-data-package.json",
	"title": "CLARITY Data Package Schema Specification",
	"description": "CLARITY Data Package is a simple specification for data access and delivery.",
	"type": "object",
	"properties": {
		"profile": {
			"$ref": "dictionary.json#/definitions/profile",
			"default": "clarity-data-package"
		},
		"name": {
			"$ref": "dictionary.json#/definitions/name"
		},
		"id": {
			"$ref": "dictionary.json#/definitions/id"
		},
		"version": {
			"title": "Version",
			"description": "A unique version number for this descriptor.",
			"type": "string",
			"pattern": "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$",
			"examples": [
				"{\n  \"version\": \"0.0.1\"\n}\n",
				"{\n  \"version\": \"1.0.1-beta\"\n}\n"
			],
			"context": "It should conform to the Semantic Versioning requirements (http://semver.org/) and should follow the Data Package Version pattern (https://frictionlessdata.io/specs/patterns/#data-package-version): MAJOR.MINOR.PATCH (e.g., 1.0.0)"
		},
		"title": {
			"$ref": "dictionary.json#/definitions/title"
		},
		"description": {
			"$ref": "dictionary.json#/definitions/description"
		},
		"homepage": {
			"$ref": "dictionary.json#/definitions/homepage"
		},
		"created": {
			"$ref": "dictionary.json#/definitions/datetime",
			"title": "Created",
			"description": "The datetime on which this descriptor was created.",
			"examples": [
				"{\n  \"created\": \"1985-04-12T23:20:50.52Z\"\n}\n"
			]
		},
		"image": {
			"$ref": "dictionary.json#/definitions/path",
			"title": "Image",
			"description": "A image to represent a data package.",
			"examples": [
				"{\n  \"image\": \"http://example.com/image.jpg\"\n}\n",
				"{\n  \"image\": \"relative/to/image.jpg\"\n}\n"
			]
		},
		"keywords": {
			"title": "Keywords",
			"description": "A list of keywords that describe this package.",
			"type": "array",
			"minItems": 1,
			"uniqueItems": true,
			"items": {
				"type": "string"
			},
			"examples": [
				"{\n  \"keywords\": [\n    \"data\",\n    \"hazard\",\n    \"eu-gl\"\n  ]\n}\n"
			]
		},
		"language": {
			"$ref": "dictionary.json#/definitions/language"
		},
		"contributors": {
			"$ref": "dictionary.json#/definitions/contributors"
		},
		"licenses": {
			"$ref": "dictionary.json#/definitions/licenses"
		},
		"sources": {
			"$ref": "dictionary.json#/definitions/sources"
		},
		"price": {
			"title": "Price",
			"description": "The monetary cost at which the data package is offered (in EURO if not indicated otherwise).",
			"type": "object",
			"properties": {
				"amount": {
					"title": "Amount",
					"description": "The price of the data package. If the data package is free, then the value of this parameter MUST be 0.0",
					"type": "number",
					"minimum": 0.0,
					"default": 0.0
				},
				"currency": {
					"title": "Currency",
					"description": "The currency property of a price is given. \n\nIt MUST be one of the codes listed here: https://www.currency-iso.org/en/home/tables/table-a1.html. By default, the currency code is \"EUR\"",
					"type": "string",
					"pattern": "^[A-Z]{3}$"
				}
			},
			"required": [
				"amount",
				"currency"
			]
		},
		"spatial_extent": {
			"$ref": "dictionary.json#/definitions/spatialExtent"
		},
		"temporal_extent": {
			"$ref": "dictionary.json#/definitions/temporalExtent"
		},
		"metadata": {
			"$ref": "dictionary.json#/definitions/metadata"
		},
		"resources": {
			"$ref": "clarity-data-resource.json#/definitions/resources"
		},
		"css_style": {
			"title": "CSS Style",
			"description": "The css_style property is a pointer to a default CSS file containing the styling configuration for several elements within the data package (e.g., threholds values colouring, vector and raster maps colouring, etc.).\n\nPlease, check the following links for further information:\n# https://www.w3.org/TR/css-2018/ \n# https://docs.geoserver.org/latest/en/user/styling/css/cookbook/index.html",
			"$ref": "dictionary.json#/definitions/path"
		}
	},
	"required": [
		"profile",
		"name",
		"id",
		"version",
		"title",
		"description",
		"created",
		"resources"
	]
}

=== clarity-h2020/data-package/examples/dc1-naples/datapackage.json
{
  "name": "dc1-naples",
  "id": "http://github.com/clarity-h2020/data-package/examples/dc1-naples",
  "version": "0.0.1",
  "profile": "http://github.com/clarity-h2020/data-package/schemas/clarity-data-package.json",
  "title": "Naples Metropolitan Area data package",
  "description": "This is the CLARITY data package for the Naples metropolitan area corresponding to the Demonstrator Case (DC1). \r\n Further description to be completed",
  "keywords": [
    "naples",
    "dc1",
    "TBC"
  ],
  "created": "2019-01-02T16:23:43Z",
  "homepage": "http://www.clarity-h2020.eu",
  "language": "eng",
  "price": {
    "amount": 0.0,
    "currency": "EUR"
  },
  "sources": [],
  "contributors": [
    {
      "title": "Miguel Ángel Esbrí",
      "role": "author",
      "email": "miguel.esbri@atos.net",
      "organization": "Atos Spain",
      "path": "http://atos.net"
    },
    {
      "title": "Mario Núñez",
      "role": "author",
      "email": "mario.nunez@atos.net",
      "organization": "Atos Spain",
      "path": "http://atos.net"
    },
    {
      "title": "",
      "role": "author",
      "email": "",
      "organization": "PLINIVS",
      "path": ""
    },
    {
      "title": "",
      "role": "author",
      "email": "",
      "organization": "ZAMG",
      "path": ""
    },
    {
      "title": "",
      "role": "author",
      "email": "",
      "organization": "METEOGRID",
      "path": ""
    }
  ],
  "licenses": [
    {
      "name": "CC0-1.0",
      "title": "Creative Commons CCZero 1.0",
      "path": "https://creativecommons.org/publicdomain/zero/1.0/"
    }
  ],
  "image": "data/logo/MyCS_48x48.png",
  "resources": [
    {
      "id": "http://github.com/clarity-h2020/data-package/examples/dc1-naples#r1",
      "name": "agricultural-areas",
      "title": "Agricultural areas in Naples metropolitan area",
      "description": "Agricultural areas in Naples metropolitan area",
      "profile": "http://github.com/clarity-h2020/data-package/schemas/clarity-data-package-resource.json",
      "encoding": "binary",
      "format": "shape-zip",
      "mediatype": "application/shape-zip",
      "bytes": "37087552",
      "hash": "tbc",
      "path": "http://services.clarity-h2020.eu:8080/geoserver/clarity/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=clarity:agricultural_areas&outputFormat=shape-zip",
      "schema": {
        "fields": [
          {
            "name": "gid",
            "title": "gid",
            "type": "integer"
          },          
          {
            "name": "geometry",
            "title": "geometry",
            "type": "polygon"
          },
          {
            "name": "area",
            "title": "area",
            "type": "double"
          },
          {
            "name": "perimeter",
            "title": "perimeter",
            "type": "double"
          },
          {
            "name": "code2012",
            "title": "code2012",
            "type": "string"
          },
          {
            "name": "albedo",
            "title": "albedo",
            "type": "double"
          },
          {
            "name": "emissivity",
            "title": "emissivity",
            "type": "double"
          },
          {
            "name": "transmissivity",
            "title": "transmissivity",
            "type": "double"
          },
          {
            "name": "vegetation_shadow",
            "title": "vegetation shadow",
            "type": "integer"
          },
          {
            "name": "run_off_coefficient",
            "title": "run off coefficient",
            "type": "double"
          },
          {
            "name": "building_shadow",
            "title": "building shadow",
            "type": "integer"
          }
        ]
      },
      "sources": [],
      "licenses": [
        {
          "name": "CC0-1.0",
          "title": "Creative Commons CCZero 1.0",
          "path": "https://creativecommons.org/publicdomain/zero/1.0/"
        }
      ],
      "protocol": "ogc:wfs",
      "mapview": {
        "service_type": "ogc:wms",
        "url": "http://services.clarity-h2020.eu:8080/geoserver/clarity/ows?service=WMS&version=1.1.0&request=GetMap&layers=clarity:agricultural_areas&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fpng"
      },
      "spatial_context": {
        "crs": "EPSG:3035",
        "extent": {
          "xmin": 0.0,
          "ymin": 0.0,
          "xmax": 0.0,
          "ymax": 0.0
        },
        "resolution": {
          "scale": 50000
        }
      },
      "eu_gl_context": {
        "workflow_step": "any",
        "hazard": "any",
        "resource_type": "feature-parameters"
      }
    },
    {
      "id": "http://github.com/clarity-h2020/data-package/examples/dc1-naples#r2",
      "name": "hot-days-historical_19710101-20001231",
      "title": "Hot days > 75th percentile for the baseline emissions scenario in the 1971-2000 period",
      "description": "Number of days per year with a mean air temperature at 2 m above ground above the 75th percentile during summer months (Apr-Sep) for the baseline emissions scenario in the 1971-2000 period",
      "profile": "http://github.com/clarity-h2020/data-package/schemas/clarity-data-package-resource.json",
      "format": "tif",
      "mediatype": "application/x-gzip",
      "bytes": "358616146",
      "hash": "tbc",
      "path": "https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_day_19710101-20001231_netcdf3&FORMAT=application/x-gzip",
      "schema": {},
      "sources": [],
      "licenses": [
        {
          "name": "CC0-1.0",
          "title": "Creative Commons CCZero 1.0",
          "path": "https://creativecommons.org/publicdomain/zero/1.0/"
        }
      ],
      "protocol": "ogc:wcs",
      "mapview": {
        "service_type": "ogc:wms",
        "url": "https://clarity.meteogrid.com/geoserver/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_historical_r12i1p1_SMHI-RCA4_v1_day_19710101-20001231_netcdf3&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fpng"
      },
      "spatial_context": {
        "crs": "EPSG:3035",
        "extent": {
          "xmin": 2145500,
          "ymin": 982500,
          "xmax": 6606000,
          "ymax": 5706500
        },
        "resolution": {
          "distance": 500,
          "uom": "m"
        },
        "grid_info": {
          "band_count": 1,
          "bit_depth": "unsigned-32-bit",
          "columns": 9448,
          "rows": 8921,
          "no_data_value": 1e+20,
          "start_cell": "top-left",
          "compression_type": "none"
        }
      },
      "temporal_context": {
        "trs": "ISO 8601:2004",
        "extent": {
          "start": "1971-01-01",
          "end": "2000-12-31"
        }
      },
      "eu_gl_context": {
        "workflow_step": "hazard-characterization",
        "hazard": "hazard:heat:extreme-heat",
        "resource_type": "index",
        "index": "hazard:heat:extreme-heat:index:hot-days-75p",
        "emissions_scenario": "baseline",
        "threshold": [
          {
            "name": "low",
            "lower": "to-be-defined"
          },
          {
            "name": "medium",
            "lower": "to-be-defined",
            "upper": "to-be-defined"
          },
          {
            "name": "high",
            "upper": "to-be-defined"
          }
        ]
      }
    },
    {
      "id": "http://github.com/clarity-h2020/data-package/examples/dc1-naples#r3",
      "name": "hot-days-rcp26_20110101-20401231",
      "title": "Hot days > 75th percentile for the rcp26 emissions scenario in the 2011-2040 period",
      "description": "Number of days per year with a mean air temperature at 2 m above ground above the 75th percentile during summer months (Apr-Sep) for the rcp26 emissions scenario in the 2011-2040 period",
      "profile": "http://github.com/clarity-h2020/data-package/schemas/clarity-data-package-resource.json",
      "format": "tif",
      "mediatype": "application/x-gzip",
      "bytes": "358616146",
      "hash": "tbc",
      "path": "https://clarity.meteogrid.com/geoserver/wcs?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3&FORMAT=application/x-gzip",
      "schema": {},
      "sources": [],
      "licenses": [
        {
          "name": "CC0-1.0",
          "title": "Creative Commons CCZero 1.0",
          "path": "https://creativecommons.org/publicdomain/zero/1.0/"
        }
      ],
      "protocol": "ogc:wcs",
      "mapview": {
        "service_type": "ogc:wms",
        "url": "https://clarity.meteogrid.com/geoserver/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp26_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf&bbox=2145500.0%2C982500.0%2C6606000.0%2C5706500.0&width=725&height=768&srs=EPSG%3A3035&format=image%2Fpng"
      },
      "spatial_context": {
        "crs": "EPSG:3035",
        "extent": {
          "xmin": 2145500,
          "ymin": 982500,
          "xmax": 6606000,
          "ymax": 5706500
        },
        "resolution": {
          "distance": 500,
          "uom": "m"
        },
        "grid_info": {
          "band_count": 1,
          "bit_depth": "unsigned-32-bit",
          "columns": 9448,
          "rows": 8921,
          "no_data_value": 1e+20,
          "start_cell": "top-left",
          "compression_type": "none"
        }
      },
      "temporal_context": {
        "trs": "ISO 8601:2004",
        "extent": {
          "start": "2011-01-01",
          "end": "2040-12-31"
        }
      },
      "eu_gl_context": {
